// ...existing code...
import { RouterModule } from '@angular/router';
// ...existing code...
@NgModule({
  // ...existing code...
  imports: [
    // ...existing code...
    RouterModule,
    // ...existing code...
  ],
  // ...existing code...
})
// ...existing code...
/* Basic styles for SidebarComponent */
li.active {
  font-weight: bold;
}
